GOOGLE_CREDENTIALS

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -31,7 +31,12 @@ jobs:
           GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
         run: |
           echo "$GOOGLE_CREDENTIALS" > $HOME/gcloud-key.json
-          cat $HOME/gcloud-key.json # Add this line to print the contents for debugging
+          echo "Google Cloud Credentials:"
+          cat $HOME/gcloud-key.json
+          if ! jq . $HOME/gcloud-key.json > /dev/null; then
+            echo "Invalid JSON in GOOGLE_CREDENTIALS"
+            exit 1
+          fi
 
       - name: Set GOOGLE_APPLICATION_CREDENTIALS
         run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json" >> $GITHUB_ENV
