debug 7

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -33,9 +33,7 @@ jobs:
           echo "$GOOGLE_CREDENTIALS" > $HOME/gcloud-key.json
           echo "Google Cloud Credentials:"
           cat $HOME/gcloud-key.json
-          if ! jq . $HOME/gcloud-key.json > /dev/null; then
-            echo "Invalid JSON in GOOGLE_CREDENTIALS"
-            exit 1
+          jq . $HOME/gcloud-key.json > /dev/null || (echo "Invalid JSON in GOOGLE_CREDENTIALS" && exit 1)
 
       - name: Set GOOGLE_APPLICATION_CREDENTIALS
         run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud-key.json" >> $GITHUB_ENV
